### ISSUE TITLE
Unable to find image 'root/copyserver:latest' locally

### ISSUE THREAD

**Issue by manojprithvee** [ianmiell/shutit_copyserver#5]

**Comment by ianmiell** [comment]
Can you post full debug output?

**Comment by manojprithvee** [comment]
Every thing run successfully but got this error when I tried toenter the
docker

**Comment by manojprithvee** [comment]
root@ip-172-31-55-134:~/shutit_copyserver/bin# ./copy_server.sh 
~/shutit_copyserver ~/shutit_copyserver/bin
# ShutIt Started... 
# Loading configs...
2016-12-04 12:29:52,751 INFO: Correcting insecure file permissions on: configs/build.cnf
2016-12-04 12:29:52,757 INFO: ShutIt modules loaded
2016-12-04 12:29:52,757 INFO: Configuration loaded
2016-12-04 12:29:52,930 INFO: Sending: PS1='ip''-172-31-55-134:ORIGIN_ENV:ijjqL21A# '
2016-12-04 12:29:52,981 INFO: Output (squashed): ip-172-31-55-134:ORIGIN_ENV:ij [...]
2016-12-04 12:29:53,775 INFO: Sending: PS1='ip''-172-31-55-134:root:teR4vi3o# '
2016-12-04 12:29:53,827 INFO: Output (squashed): ip-172-31-55-134:root:teR4vi3o [...]
2016-12-04 12:29:54,409 INFO: Connected to target



Please input a value for shutit.shutit_copyserver.shutit_copyserver.shutit_copyserver.base_image

Please input an appropriate docker base image, eg:
ubuntu
ubuntu:12.04
centos

You can use any base image you want, but be aware that non-apt or yum-based images are less likely to succeed.: 
ubuntu
2016-12-04 12:30:13,108 INFO: Sending: PS1='ip''-172-31-55-134:shutit.tk.setup:m02SQruL# '
2016-12-04 12:30:13,160 INFO: Output (squashed): ip-172-31-55-134:shutit.tk.set [...]
2016-12-04 12:30:14,430 INFO: Sending: PS1='ip''-172-31-55-134:shutit.shutit_copyserver.shutit_copyserver.shutit_copyserver:1Rj3RwjR# '
2016-12-04 12:30:14,484 INFO: Output (squashed): ip-172-31-55-134:shutit.shutit [...]
2016-12-04 12:30:15,382 INFO: Considering whether to build: shutit.tk.setup
2016-12-04 12:30:15,752 INFO: Sending: PS1='ip''-172-31-55-134:shutit.tk.setup:Z7TMhDOA# '
2016-12-04 12:30:15,804 INFO: Output (squashed): ip-172-31-55-134:shutit.tk.set [...]
2016-12-04 12:30:16,438 INFO: Building ShutIt module: shutit.tk.setup with run order: 0
2016-12-04 12:30:16,592 INFO: Considering whether to build: shutit.shutit_copyserver.shutit_copyserver.shutit_copyserver
2016-12-04 12:30:16,964 INFO: Sending: PS1='ip''-172-31-55-134:shutit.shutit_copyserver.shutit_copyserver.shutit_copyserver:XGsDszdx# '
2016-12-04 12:30:17,018 INFO: Output (squashed): ip-172-31-55-134:shutit.shutit [...]
2016-12-04 12:30:17,660 INFO: Building ShutIt module: shutit.shutit_copyserver.shutit_copyserver.shutit_copyserver with run order: 1161086295
2016-12-04 12:30:17,660 INFO: Matching output from: "whoami" to one of these regexps:root
2016-12-04 12:30:17,713 INFO: Installing package: python-pip
2016-12-04 12:30:17,765 INFO: Sending: apt-get update
2016-12-04 12:30:20,724 INFO: Output (squashed): 0% [Working]            Hit:1  [...]
2016-12-04 12:30:20,828 INFO: Sending: DEBIAN_FRONTEND=noninteractive apt-get install -y -qq  python-pip
2016-12-04 12:30:21,151 INFO: Output (squashed): ip-172-31-55-134:shutit.shutit [...]
2016-12-04 12:30:21,255 INFO: Sending: DEBIAN_FRONTEND=noninteractive apt-get install -y -qq  python-pip
2016-12-04 12:30:21,573 INFO: Output (squashed): ip-172-31-55-134:shutit.shutit [...]
2016-12-04 12:30:21,677 INFO: Sending: DEBIAN_FRONTEND=noninteractive apt-get install -y -qq  python-pip
2016-12-04 12:30:21,993 INFO: Output (squashed): ip-172-31-55-134:shutit.shutit [...]
2016-12-04 12:30:22,045 INFO: Installing package: git
2016-12-04 12:30:22,097 INFO: Sending: DEBIAN_FRONTEND=noninteractive apt-get install -y -qq  git
2016-12-04 12:30:22,418 INFO: Output (squashed): ip-172-31-55-134:shutit.shutit [...]
2016-12-04 12:30:22,522 INFO: Sending: DEBIAN_FRONTEND=noninteractive apt-get install -y -qq  git
2016-12-04 12:30:22,846 INFO: Output (squashed): ip-172-31-55-134:shutit.shutit [...]
2016-12-04 12:30:22,950 INFO: Sending: DEBIAN_FRONTEND=noninteractive apt-get install -y -qq  git
2016-12-04 12:30:23,274 INFO: Output (squashed): ip-172-31-55-134:shutit.shutit [...]
2016-12-04 12:30:23,325 INFO: Matching output from: "git config -l" to one of these regexps:user.email
2016-12-04 12:30:23,378 INFO: Matching output from: "git config -l" to one of these regexps:user.name
2016-12-04 12:30:23,431 INFO: Sending: rm -rf /tmp/shutit_copyserver
2016-12-04 12:30:23,484 INFO: Output (squashed): ip-172-31-55-134:shutit.shutit [...]
2016-12-04 12:30:23,535 INFO: Sending: pip install blueprint
2016-12-04 12:30:24,448 INFO: Output (squashed): Requirement already satisfied  [...]
2016-12-04 12:30:24,500 INFO: Sending: echo ':package:apt/docker' >> /etc/blueprintignore
2016-12-04 12:30:24,552 INFO: Output (squashed): ip-172-31-55-134:shutit.shutit [...]
2016-12-04 12:30:24,604 INFO: Sending: echo ':package:apt/docker.io' >> /etc/blueprintignore
2016-12-04 12:30:24,656 INFO: Output (squashed): ip-172-31-55-134:shutit.shutit [...]
2016-12-04 12:30:24,708 INFO: Sending: echo ':package:apt/docker-engine' >> /etc/blueprintignore
2016-12-04 12:30:24,760 INFO: Output (squashed): ip-172-31-55-134:shutit.shutit [...]
2016-12-04 12:30:24,812 INFO: Sending: echo ':package:apt/virtualbox' >> /etc/blueprintignore
2016-12-04 12:30:24,864 INFO: Output (squashed): ip-172-31-55-134:shutit.shutit [...]
2016-12-04 12:30:24,916 INFO: Sending: echo ':package:apt/virtualbox-dkms' >> /etc/blueprintignore
2016-12-04 12:30:24,968 INFO: Output (squashed): ip-172-31-55-134:shutit.shutit [...]
2016-12-04 12:30:25,020 INFO: Sending: echo ':package:apt/virtualbox-qt' >> /etc/blueprintignore
2016-12-04 12:30:25,073 INFO: Output (squashed): ip-172-31-55-134:shutit.shutit [...]
2016-12-04 12:30:25,124 INFO: Sending: shutit skeleton --output_dir --base_image ubuntu --pattern docker --name /tmp/shutit_copyserver --domain shutit.copied_server --delivery docker
2016-12-04 12:30:25,356 INFO: Output (squashed): # ShutIt Started... # Loading  [...]
2016-12-04 12:30:25,408 INFO: Sending: cd /tmp/shutit_copyserver
2016-12-04 12:30:25,459 INFO: Output (squashed): ip-172-31-55-134:shutit.shutit [...]
2016-12-04 12:30:25,511 INFO: Sending: blueprint create shutit_copyserver
2016-12-04 12:30:41,980 INFO: Output (squashed): # [blueprint] searching for AP [...]
2016-12-04 12:30:42,032 INFO: Sending: blueprint show -S shutit_copyserver
2016-12-04 12:30:42,205 INFO: Output (squashed): shutit_copyserver/bootstrap.sh [...]
2016-12-04 12:30:42,257 INFO: Sending: sed -i 's/^...n "$SERVICE_.*$//g' shutit_copyserver/bootstrap.sh
2016-12-04 12:30:42,323 INFO: Output (squashed): ip-172-31-55-134:shutit.shutit [...]
2016-12-04 12:30:43,277 INFO: Sending: PS1='ip''-172-31-55-134:shutit.shutit_copyserver.shutit_copyserver.shutit_copyserver:LaeJFb02# '
2016-12-04 12:30:43,331 INFO: Output (squashed): ip-172-31-55-134:shutit.shutit [...]
2016-12-04 12:30:44,289 INFO: Sending: PS1='ip''-172-31-55-134:shutit.tk.setup:awXvbDAa# '
2016-12-04 12:30:44,341 INFO: Output (squashed): ip-172-31-55-134:shutit.tk.set [...]
2016-12-04 12:30:45,296 INFO: Sending: PS1='ip''-172-31-55-134:shutit.shutit_copyserver.shutit_copyserver.shutit_copyserver:RN8BvipH# '
2016-12-04 12:30:45,350 INFO: Output (squashed): ip-172-31-55-134:shutit.shutit [...]
2016-12-04 12:30:46,309 INFO: Sending: PS1='ip''-172-31-55-134:shutit.tk.setup:PirwiATE# '
2016-12-04 12:30:46,361 INFO: Output (squashed): ip-172-31-55-134:shutit.tk.set [...]
2016-12-04 12:30:47,096 INFO: ShutIt run finished
~/shutit_copyserver/bin

**Comment by ianmiell** [comment]
OK, can you run a fresh checkout of my repo, and run:

./copy_server.sh -l debug

**Comment by manojprithvee** [comment]
the file has the output that i got
[log.txt](https://github.com/ianmiell/shutit_copyserver/files/634011/log.txt)

**Comment by jyapayne** [comment]
I have the same issue. I'm running Ubuntu 14.04.5 on a digital ocean instance.

**Comment by ianmiell** [comment]
This looks odd:

```

2016-12-06 13:47:39,202 DEBUG: ================================================================================
2016-12-06 13:47:39,202 DEBUG: Sending>>>/root/.shutit/shutit build -s repository tag yes -s repository name copyserver -l DEBUG<<<
2016-12-06 13:47:39,202 DEBUG: Expecting>>>['shutit appears not', 'ip-172-31-55-134:shutit.shutit_copyserver.shutit_copyserver.shutit_copyserver:lqw2oQXK# ']<<<
/root/.shutit/shutit build -s repository tag yes -s repository name copyserver -l DEBUG
/root/.shutit/shutit build -s repository tag yes -s repository name copyserver -l DEBUG
bash: /root/.shutit/shutit: No such file or directory
ip-172-31-55-134:shutit.shutit_copyserver.shutit_copyserver.shutit_copyserver:lqw2oQXK# 2016-12-06 13:47:39,256 DEBUG: Output (squashed): bash: /root/.shutit/shutit: No [...]
2016-12-06 13:47:39,256 DEBUG: shutit_pexpect_child.buffer(hex)>>>

<<<
2016-12-06 13:47:39,256 DEBUG: shutit_pexpect_child.buffer>>>

<<<
2016-12-06 13:47:39,256 DEBUG: shutit_pexpect_child.before (hex)>>>
2f726f6f742f2e7368757469742f736875746974206275696c64202d73207265706f7369746f72792074616720796573202d73207265706f7369746f7279206e616d6520636f7079736572766572202d6c2044454255470d0a626173683a202f726f6f742f2e7368757469742f7368757469743a204e6f20737563682066696c65206f72206469726563746f72790d0a
<<<
2016-12-06 13:47:39,256 DEBUG: shutit_pexpect_child.before>>>
/root/.shutit/shutit build -s repository tag yes -s repository name copyserver -l DEBUG
bash: /root/.shutit/shutit: No such file or directory

<<<
2016-12-06 13:47:39,256 DEBUG: shutit_pexpect_child.after (hex)>>>
69702d3137322d33312d35352d3133343a7368757469742e7368757469745f636f70797365727665722e7368757469745f636f70797365727665722e7368757469745f636f70797365727665723a6c7177326f51584b2320
<<<
2016-12-06 13:47:39,257 DEBUG: shutit_pexpect_child.after>>>
ip-172-31-55-134:shutit.shutit_copyserver.shutit_copyserver.shutit_copyserver:lqw2oQXK# 
<<<
2016-12-06 13:47:39,257 DEBUG: Retrieving output from command: exit
2016-12-06 13:47:39,257 DEBUG: Sending data in session: target_child
2016-12-06 13:47:39,257 DEBUG: Sending: exit
```

**Comment by Kerbobotat** [comment]
Any update on this issue? Im experiencing the same issue. ShutIt run finishes, but no image is created.

**Comment by manojprithvee** [comment]
No I made it from scratch in to a docker compose script it's not that
difficult took me 5 days and I use mysql,redis, Cassandra,rails,java in my
stack

**Comment by jsconsultancy** [comment]
Got the following error. 

[root@localhost bin]# ./copy_server.sh -l debug                                 ~/shutit_copyserver/bin/shutit_copyserver ~/shutit_copyserver/bin/shutit_copyserver/bin
/usr/lib/python2.6/site-packages/shutit_pexpect.py:46: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  from md5 import md5
Traceback (most recent call last):
  File "/usr/bin/shutit", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.6/site-packages/shutit.py", line 50, in main
    if sys.version_info.major == 2:
AttributeError: 'tuple' object has no attribute 'major'
~/shutit_copyserver/bin/shutit_copyserver/bin

**Comment by ianmiell** [comment]
After a busy few months I have some time to look at this. There are a couple of bugs I’m fixing, and testing now.

**Comment by jsconsultancy** [comment]
A couple of things. 
The above was on CentOS 6 and it was running python 2.6.6. Other errors when I installed python 2.7, there was other errors with the scripts . 
Looks like there is too much dependencies but this is really a good idea if it can wrong across different Linux OS versions, and be somewhat independent of the python versions. 
In any case, my VM is corrupted and doesn't boot properly, so once you got bug fix, I'll start all over again and test. Thanks !!
