### ISSUE TITLE
blueprint show -S shutit_copyserver  returned unaccepted exit code: 1

### ISSUE THREAD

**Issue by chemax** [ianmiell/shutit_copyserver#7]
https://pastebin.com/4gJimW2f
https://pastebin.com/dUajrz8K
Hi. Please, help me with your beatiful script. 
Debian 8.
What can i do with it?

**Comment by xstable** [comment]
Same error here on Ubuntu 12.04: 

```
# [blueprint] searching for npm packages
# [blueprint] searching for Python packages
# [blueprint] searching for configuration files
# [blueprint] /etc/ssl/certs/EBG_Elektronik_Sertifika_Hizmet_Sa\xc4\x9flay\xc4\xb1c\xc4\xb1s\xc4\xb1.pem not UTF-8 - skipping it
# [blueprint] /etc/ssl/certs/AC_Ra\xc3\xadz_Certic\xc3\xa1mara_S.A..pem not UTF-8 - skipping it
# [blueprint] /etc/ssl/certs/NetLock_Arany_=Class_Gold=_F\xc5\x91tan\xc3\xbas\xc3\xadtv\xc3\xa1ny.pem not UTF-8 - skipping it
# [blueprint] /etc/ssl/certs/Certinomis_-_Autorit\xc3\xa9_Racine.pem not UTF-8 - skipping it
# [blueprint] /etc/ssl/certs/T\xc3\x9cRKTRUST_Elektronik_Sertifika_Hizmet_Sa\xc4\x9flay\xc4\xb1c\xc4\xb1s\xc4\xb1_H5.pem not UTF-8 - skipping it
# [blueprint] /etc/ssl/certs/T\xc3\x9cB\xc4\xb0TAK_UEKAE_K\xc3\xb6k_Sertifika_Hizmet_Sa\xc4\x9flay\xc4\xb1c\xc4\xb1s\xc4\xb1_-_S\xc3\xbcr\xc3\xbcm_3.pem not UTF-8 - skipping it
# [blueprint] /etc/ssl/certs/T\xc3\x9cRKTRUST_Elektronik_Sertifika_Hizmet_Sa\xc4\x9flay\xc4\xb1c\xc4\xb1s\xc4\xb1_H6.pem not UTF-8 - skipping it
# [blueprint] searching for Yum packages
# [blueprint] searching for APT packages
# [blueprint] searching for PEAR/PECL packages
# [blueprint] searching for software built from source
# [blueprint] searching for Ruby gems
# [blueprint] searching for service dependencies
zeus:shutit.shutit_copyserver.shutit_copyserver.shutit_copyserver:FsCJA1QS# blueprint show -S shutit_copyserver
blueprint show -S shutit_copyserver
Traceback (most recent call last):
  File "/usr/local/bin/blueprint-show", line 63, in <module>
    filename = getattr(b, options.generate)(options.relaxed).dumpf()
  File "/usr/local/lib/python2.7/dist-packages/blueprint/frontend/sh.py", line 333, in dumpf
    f.write('{0}\n'.format(out))
  File "/usr/lib/python2.7/codecs.py", line 691, in write
    return self.writer.write(data)
  File "/usr/lib/python2.7/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1543: ordinal not in range(128)
zeus:shutit.shutit_copyserver.shutit_copyserver.shutit_copyserver:FsCJA1QS#  set +m && { : $(history -a) & } 2>/dev/null
 set +m && { : $(history -a) & } 2>/dev/null
zeus:shutit.shutit_copyserver.shutit_copyserver.shutit_copyserver:FsCJA1QS#

WARNING: command:
blueprint show -S shutit_copyserver

returned unaccepted exit code: 1
If this is expected, pass in check_exit=False or an exit_values array into the send function call.

Interactive, so not retrying.
Pause point on exit_code != 0 (1). CTRL-C to quit

zeus:shutit.shutit_copyserver.shutit_copyserver.shutit_copyserver:FsCJA1QS#  bash

```

**Comment by claytondukes** [comment]
I just tried on Ubuntu 16.04 and got the same error. Any update available on this?

**Comment by changchichung** [comment]
same error on ubuntu 18.04

**Comment by dandoran-wp** [comment]
You can successfully just run the build script yourself by that point: /tmp/shutit_copyserver/build.sh

By the way, please note that the documentation is inaccurate as to the name of the resulting image: it is shutit_copyserver. So execute: docker run -ti shutit_copyserver /bin/bash

**Comment by joesixpack** [comment]
Same as #6 

Not sure running build.sh after this error actually works.  The resulting image is essentially empty.

**Comment by ShivamJoker** [comment]
same on ubuntu

**Comment by sameer-j** [comment]
same on centos 7.4

**Comment by ianmiell** [comment]
I stopped maintaining this years ago as there were problems with blueprint that were not resolved upstream.
